version: '3.8'

services:
  backend:
    build: 
      context: .
      target: backend
      dockerfile: ./deploy/Dockerfile
    restart: always
    volumes:
      - ./deploy/tmp/data:/app/backend/pb_data:rw

  proxy:
    build: 
      context: .
      target: proxy
      dockerfile: ./deploy/Dockerfile
    restart: always
    volumes:
      - ./deploy/tmp/nginx/conf.d:/etc/nginx/conf.d/
      - ./deploy/tmp/certbot/www/:/var/www/certbot/:ro
      - ./deploy/tmp/certbot/conf/:/etc/letsencrypt/:ro
    ports:
      - 80:80
      - 433:433

  certbot:
    build: 
      context: .
      target: certbot
      dockerfile: ./deploy/Dockerfile
    volumes:
      - ./deploy/tmp/certbot/www/:/var/www/certbot/:rw
      - ./deploy/tmp/certbot/conf/:/etc/letsencrypt/:rw