name: CICD

on: [push]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3

     - name: Set up Go
       uses: actions/setup-go@v4
       with:
         go-version: '1.20'
         cache-dependency-path: backend/go.sum

     - name: Build
       run: |
         cd backend
         go mod download
         go build
         ls -l
        
      - name: rsync deployments
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avz
          path: ./backend/hackathon-backend
          remote_path: /var/www/pocketbase
          remote_host: ${{ secrets.HOST }}
          remote_user: ${{ secrets.USER_NAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        
     - name: Copy to linode
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USER_NAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: ${{ secrets.PORT }}
         script: |
           ls -l /var/www/pocketbase
